from __future__ import annotations

class DBusException(Exception): ...
class RemoteObject: ...

class SystemBus:
    def get_object(self, bus_name: str, object_path: str) -> RemoteObject: ...

class Interface:
    def __init__(self, obj: RemoteObject, dbus_interface: str) -> None: ...

class Boolean(int):
    def __new__(cls, value: bool) -> Boolean: ...

class UInt32(int):
    def __new__(cls, value: int) -> UInt32: ...
